spring.application.name=lost-link-backend
spring.config.import=optional:file:.env[.properties]

gemini.api-key=${GEMINI_API_KEY:${GOOGLE_API_KEY:}}
gemini.model=${GEMINI_MODEL:gemini-1.5-flash}
server.port=${PORT:8081}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=12MB
server.error.include-message=always
server.error.include-binding-errors=always
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=${MONGO_URI}